//
//  p2.swift
//  ProjectEuler-In-Swift
//
//  Created by Prakash on 12/22/14.
//  Copyright (c) 2014 prakashn. All rights reserved.
//

import Foundation
/* Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
class Problem2 {
    /* fib series :0 1 1 2 3 5 8 13 21 ..
     use modulu operator to find the minimum elements*/
    
    func evenSum(range:Int) -> String {
        var (a,b) = (0, 1)
        var sum = 0
        //println("a = \(a), b = \(b)")
        while(a < range) {
            if a % 2 == 0 {
                sum += a
            }
            (a, b) = (b, a+b)
        }
        return "P2:EvenSum of \(range) is \(sum)"
    }

}
